# Generated by Django 4.1.6 on 2023-02-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductCategory', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductDesc', models.CharField(max_length=250)),
                ('ProductPrice', models.IntegerField()),
                ('ProductImage', models.ImageField(default='', upload_to='Photos')),
            ],
        ),
    ]
