# Generated by Django 4.1.6 on 2023-02-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudKitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('ProductId', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductCategory', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductPrice', models.IntegerField()),
                ('ProductImage', models.ImageField(default='', upload_to='Photos')),
            ],
        ),
    ]
