# Generated by Django 4.1.6 on 2023-02-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudKitchen', '0002_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='ProductImage',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='ProductCategory',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='ProductId',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='ProductName',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ProductImage',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ProductCategory',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ProductDesc',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ProductId',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ProductName',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ProductPrice',
            new_name='product_price',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='ProductPrice',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='product_uom',
            field=models.CharField(default='Dish', max_length=10),
        ),
    ]
