# Generated by Django 4.1.6 on 2023-02-17 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloudKitchen', '0005_orderitem_delete_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(default='Sk Samrat', max_length=50)),
                ('seller_name', models.CharField(default='Jayanta Dutta', max_length=50)),
                ('total_price', models.IntegerField()),
                ('order_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_uom',
            field=models.CharField(default='Dish', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudKitchen.order', to_field='order_id'),
        ),
    ]
