# Generated by Django 4.1.6 on 2023-02-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloudKitchen', '0006_order_orderitem_product_uom_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(default='ORID00000001', on_delete=django.db.models.deletion.CASCADE, to='CloudKitchen.order', to_field='order_id'),
        ),
    ]
