# Generated by Django 4.1.6 on 2023-02-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloudKitchen', '0008_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
