# Generated by Django 4.1.6 on 2023-02-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudKitchen', '0009_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(default='Sk Samrat', max_length=50)),
                ('seller_name', models.CharField(default='Jayanta Dutta', max_length=50)),
                ('total_price', models.IntegerField()),
                ('order_date', models.DateField()),
            ],
        ),
    ]
