# Generated by Django 4.1.6 on 2023-02-17 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloudKitchen', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudKitchen.order', to_field='order_id'),
        ),
    ]
