# Generated by Django 4.1.6 on 2023-02-20 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudKitchen', '0013_alter_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderitem_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('order_quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('product_uom', models.CharField(default='Dish', max_length=10)),
                ('total_price', models.IntegerField()),
                ('customer_name', models.CharField(default='Sk Samrat', max_length=50)),
                ('seller_name', models.CharField(default='Jayanta Dutta', max_length=50)),
                ('order_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
    ]
