# Generated by Django 4.1.6 on 2023-02-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloudKitchen', '0015_orderall_delete_orderitem_view'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderall',
            table='Order_View',
        ),
    ]
