# Generated by Django 4.1.6 on 2023-02-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloudKitchen', '0016_alter_orderall_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderall',
            table='order_all_view',
        ),
    ]
